### ISSUE TITLE
Question about contribution to this project

### ISSUE THREAD

**Issue by ChronosX88** [libp2p/jvm-libp2p#13]
Hello, I long time watching this repo and I want to help you with the implementation of libp2p under Kotlin. How can I start, and where do you discuss the development of this implementation?
@raulk

**Comment by raulk** [comment]
Hey! Thanks for reaching out. We’re gonna be promoting this project to the libp2p org, and will create a Gitter channel along the way. Will update this issue when all of that is done. Then we’ll have a venue to coordinate.

**Comment by ChronosX88** [comment]
Ok, thank you!
