### ISSUE TITLE
except for 0.4.1,none of the project can be run on WIN10

### ISSUE THREAD

**Issue by code-fool** [libp2p/jvm-libp2p#152]
it is a really surprising thing for me ,as like eveyone except for me cannot build and run this program successfully here .there are so many kinds of bugs,and the most terrible one is that the package cannot be found in list.yes ,that is the netty package in 0.5.0 ,I have to import the package of 0.4.1,witch is the only one can run ,and i have to change l line of code to make sure it .Please have l look at the publish code ,ok?no matter good or not ,at lease let the code run .
![image](https://user-images.githubusercontent.com/44488158/97975426-166ee180-1e04-11eb-8a3b-3589a81ca997.png)
I try hard ,this is the only one 
![image](https://user-images.githubusercontent.com/44488158/97975511-3900fa80-1e04-11eb-8643-2da59c86a406.png)

I have to do this ,or it will create bug

besides,is there so many people run this android program on linux or other OS?Please let me know about it ,thinks

**Comment by ajsutton** [comment]
Tests are passing on Windows GitHub actions executor now and not having any issues using jvm-libp2p on Windows in Teku. May well have been issues with these older releases but seems to be resolved in the latest versions.
