### ISSUE TITLE
mplex: implement protocol Netty handler

### ISSUE THREAD

**Issue by Nashatyrev** [libp2p/jvm-libp2p#16]
Implement the codec which will encode/decode mplex frames to/from objects like below:
```
streamId: Long
flag: MplexFrameFlag
data: ByteBuf
```
Enforce the protocol rules like correct order of frame flags, writing to closed stream, duplicate Ids, etc

**Comment by snazha-blkio** [comment]
Our stream is being closed (via a `Reset` message) because `/ipfs/id/1.0.0` is expecting an `Identify` message to have previously been sent.

Awaiting some guidance on how to handle this.
