### ISSUE TITLE
Can we fund development maybe?

### ISSUE THREAD

**Issue by veqtor** [libp2p/jvm-libp2p#180]
I'm very interested in seeing jvm-libp2p built out to cover the full extent of the libp2p spec, but I seem to see very little incentive beyond what is needed for Teku development.
I'm willing to invest some ETH in getting it built out and I'm sure others are too.
Can we perhaps bring together a funding round or something?

**Comment by ajsutton** [comment]
The current constraint is mostly about developer time.  The Teku team are the only people currently contributing and we have to balance libp2p improvements with the other areas of development.

So a funding round could be useful but only if it was aimed at hiring new developers who would focus on jvm-libp2p. The help would definitely be welcome. :)

**Comment by ajsutton** [comment]
Closing this issue because while the sentiment is appreciated, GitHub issues probably isn't going to be the place to coordinate it all happening.
