### ISSUE TITLE
noise-java will stop resolving after Feb 1

### ISSUE THREAD

**Issue by galargh** [libp2p/jvm-libp2p#201]
noise-java is currently hosted on jcenter which is being shut down with Feb 1st being the cutoff date.

Here's an issue that tracks uploading noise-java to maven-central instead of jcenter: https://github.com/rweather/noise-java/issues/9

If the above issue is not resolved until then, we might want to either go back to using source in our build or publishing the artifact ourselves.

**Comment by ajsutton** [comment]
Thanks for raising this. Looks like it would be easy to fork the repo and set it up to publish to cloudsmith which we're using for libp2p if upstream doesn't fix the issue in time which I think would be my preferred option. Then it would still be easy to pull any upstream changes in with a simple git pull - our version would only differ in the publishing.

**Comment by Nashatyrev** [comment]
I believe it was fixed with #207
