### ISSUE TITLE
Implement Ping protocol

### ISSUE THREAD

**Issue by Nashatyrev** [libp2p/jvm-libp2p#22]
https://docs.rs/libp2p-ping/0.10.0/libp2p_ping/
depends on #16

**Comment by snazha-blkio** [comment]
Implemented but on-hold until I can verify the stream impl is correct?

**Comment by jezhiggins** [comment]
The ping protocol interoperates with go libp2p without issue, both as sender and receiver. As far as I can tell it also interops with Rust libp2p (the Rust library is harder/less obvious than go).  I think it's fine and we can close this issue.

**Comment by Nashatyrev** [comment]
Implemented
