### ISSUE TITLE
[Android] Nothing works. Duplicate class

### ISSUE THREAD

**Issue by master255** [libp2p/jvm-libp2p#274]
The library (implementation 'io.libp2p:jvm-libp2p-minimal:0.10.0-RELEASE') does not compile in Android Studio. There are a lot of errors:

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class io.netty.channel.epoll.AbstractEpollChannel found in the following modules: jetified-netty-transport-native-epoll-4.1.69-linux-aarch_64.Final-linux-aarch_64 (io.netty:netty-transport-native-epoll:4.1.69.Final), jetified-netty-transport-native-epoll-4.1.69-linux-x86_64.Final-linux-x86_64 (io.netty:netty-transport-native-epoll:4.1.69.Final) and jetified-netty-transport-native-epoll-4.1.69.Final (io.netty:netty-transport-native-epoll:4.1.69.Final)
     Duplicate class io.netty.channel.epoll.AbstractEpollChannel$1 found in the following modules: jetified-netty-transport-native-epoll-4.1.69-linux-aarch_64.Final-linux-aarch_64 (io.netty:netty-transport-native-epoll:4.1.69.Final), jetified-netty-transport-native-epoll-4.1.69-linux-x86_64.Final-linux-x86_64 (io.netty:netty-transport-native-epoll:4.1.69.Final) and jetified-netty-transport-native-epoll-4.1.69.Final (io.netty:netty-transport-native-epoll:4.1.69.Final)
     Duplicate class io.netty.channel.epoll.AbstractEpollChannel$2 found in the following modules: jetified-netty-transport-native-epoll-4.1.69-linux-aarch_64.Final-linux-aarch_64 (io.netty:netty-transport-native-epoll:4.1.69.Final), jetified-netty-transport-native-epoll-4.1.69-linux-x86_64.Final-linux-x86_64 (io.netty:netty-transport-native-epoll:4.1.69.Final) and jetified-netty-transport-native-epoll-4.1.69.Final (io.netty:netty-transport-native-epoll:4.1.69.Final)
     
     2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 32 files found with path 'META-INF/INDEX.LIST' from inputs:
      - C:\Users\Oleg\.gradle\caches\transforms-3\173ef897e3d739b1f8d85f8c0a85012d\transformed\jetified-netty-all-4.1.69.Final.jar
      - C:\Users\Oleg\.gradle\caches\transforms-3\6862ae8525f3f5020ae995a4615b8433\transformed\jetified-netty-transport-native-epoll-4.1.69.Final.jar
      - C:\Users\Oleg\.gradle\caches\transforms-3\3ce746b28e50474cf0068ce24dd605a1\transformed\jetified-netty-transport-native-epoll-4.1.69.Final-linux-x86_64.jar
      - C:\Users\Oleg\.gradle\caches\transforms-3\b6c37b5b1b457ed1498f15b2b1fd5491\transformed\jetified-netty-transport-native-epoll-4.1.69.Final-linux-aarch_64.jar
      - C:\Users\Oleg\.gradle\caches\transforms-3\1688c8b067d5e75eff9868f6c3233b46\transformed\jetified-netty-transport-native-kqueue-4.1.69.Final.jar
      - C:\Users\Oleg\.gradle\caches\transforms-3\07802a487aa666dfaea3f3c85efa3b3d\transformed\jetified-netty-transport-native-kqueue-4.1.69.Final-osx-x86_64.jar

**Comment by master255** [comment]
@HarshPanchal18 This error occurs on an empty project.

**Comment by master255** [comment]
@HarshPanchal18 What dependencies did you add to make it disappear?

**Comment by master255** [comment]
@HarshPanchal18 No. It doesn't help. The library doesn't work.

**Comment by master255** [comment]
It seems I'm the only one in the world who wants to run libp2p on Android.

**Comment by master255** [comment]
@HarshPanchal18 As you can see I'm here and I'm trying to talk to a developer. He's not answering.

**Comment by master255** [comment]
@Nashatyrev @jezhiggins @shahankhatch @ajsutton @protocol @jtraglia @ianopolous Someone tell me how to use this library in Android?

**Comment by master255** [comment]
@HarshPanchal18 It looks like the project is dead, and so are the developers. Or it's secret information.

**Comment by master255** [comment]
@Nashatyrev I checked. [These errors](https://github.com/libp2p/jvm-libp2p/issues/274#issue-1704720274) occur on an empty, new project. This branch I do not know how to test, because the project does not compile.

**Comment by master255** [comment]
My Android Studio version: Android Studio Flamingo | 2022.2.1 Patch 1 and nothing works.

**Comment by master255** [comment]
@Nashatyrev After compiling I get a file like this. Which gives me an error when I create the Host.
[libp2p-develop jar.zip](https://github.com/libp2p/jvm-libp2p/files/11481297/libp2p-develop.jar.zip)

**Comment by Nashatyrev** [comment]
@master255 sorry, didn't get the original case you were complaining about. 
You are trying to pull the jvm-libp2p as a dependency. 

Here are modifications I've come up with to compile Android project: 
1. Include additional repository: 
```gradle
dependencyResolutionManagement {
    repositories {
        // ....
        maven { url "https://dl.cloudsmith.io/public/libp2p/jvm-libp2p/maven/" }
        maven { url "https://artifacts.consensys.net/public/maven/maven/" }
    }
}
```
2. Exclude Netty native transitive modules (they are not used but included by `netty-all` artifact. This is to be sorted out, since jvm-libp2p doesn't need most of dependencies included by `netty-all`):
```gradle
dependencies {
    // ....
    implementation('io.libp2p:jvm-libp2p-minimal:0.10.0-RELEASE') {
        exclude group: 'io.netty', module: 'netty-transport-native-epoll'
        exclude group: 'io.netty', module: 'netty-transport-native-kqueue'
        exclude group: 'io.netty', module: 'netty-resolver-dns-native-macos'
    }
    // ....
}
```
3. Exclude duplicated resources from packaging:
```gradle
android {
    // ...
    packagingOptions {
        resources {
            // ...
            excludes += 'META-INF/INDEX.LIST'
            excludes += 'META-INF/DEPENDENCIES'
            excludes += 'META-INF/io.netty.versions.properties'
        }
    }
}
```

**Comment by master255** [comment]
Okay. I was able to start the project. This required me to raise the minimum api to 26.

**Comment by master255** [comment]
@Nashatyrev And is there even one example of how the library works? Nothing works. No pinger, no chatter... just a dead library.
What can I do to just pass a string from computer 1 to computer 2?

**Comment by master255** [comment]
Another error when running an empty application with these parameters:

```
Installation did not succeed.
The application could not be installed: INSTALL_FAILED_NO_MATCHING_ABIS

List of apks:
[0] 'C:\Users\Oleg\Documents\MyApplication\app\build\intermediates\apk\debug\app-debug.apk'
Installation failed due to: 'Failed to commit install session 1479165950 with command cmd package install-commit 1479165950. Error: INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113'
Retry
Failed to launch an application on all devices
```

**Comment by master255** [comment]
Ok. No one said and nowhere is it written that I need to compile the go-libp2p library itself and add it to the project. Is this true?
I added it to the project and then everything started working.

I was able to create a chat and send a message.
