### ISSUE TITLE
What is the point of this library?

### ISSUE THREAD

**Issue by master255** [libp2p/jvm-libp2p#288]
@Nashatyrev Perhaps I am misunderstanding something. But for Android it is possible to write code in Golang and use it, as [in my example.](https://github.com/libp2p/go-libp2p/issues/2282#issuecomment-1546903352)
This library is a kind of swig - i.e. a set of methods to work with the go-libp2p library? I.e. it's for those who don't want to write code in Golang and want to write only in Kotlin/Java?
Or is there something I don't know?

**Comment by jeesk** [comment]
Can C++also write code? What do you need Golang for?

Can assembly also write code? What do you need Java for?

**Comment by master255** [comment]
Golang is needed to write goLibp2p. In C++ this library does not exist.
Assembler is too complicated to write an Android application. That's why everyone uses Java for Android.
