### ISSUE TITLE
Host.addProtocolHandler doesn't work

### ISSUE THREAD

**Issue by ianopolous** [libp2p/jvm-libp2p#296]
If I add a protocol to a running host, then new incoming connections do not see the added protocol in the protocol negotiation. 

I'm hoping to find a fix and submit a PR.

**Comment by ianopolous** [comment]
I have a fix, but will wait until https://github.com/libp2p/jvm-libp2p/pull/295 is merged before PRing it.

**Comment by Nashatyrev** [comment]
Fixed with #299
