### ISSUE TITLE
circuit-relay-v2

### ISSUE THREAD

**Issue by ianopolous** [libp2p/jvm-libp2p#344]
Hi @Nashatyrev et al,

I'm working on an implementation of circuit-relay-v2 in another repo and would like to upstream it, if you are interested, when it is working. Is this something you'd like upstreamed?

I've got the relay working, and relaying connections. I'm just working on adding the security and muxer upgrade to relayed streams. I've implemented a new RelayTransport and made sure TcpTransport won't try and handle circuit addresses. 

What are you thoughts on the direction of this: https://github.com/Peergos/nabu/compare/feat/circuit-relay-v2?expand=1

The important bit is HostBuilder::upgradeConnection for handling incoming relayed connections. Once this is done I'll work on dcutr.

**Comment by Nashatyrev** [comment]
Hey @ianopolous 

> What are you thoughts on the direction of this: https://github.com/Peergos/nabu/compare/feat/circuit-relay-v2?expand=1

That doesn't look like a lot of changes to the core classes there. I believe it's worth to upstream. 
@StefanBratanov what do you think?

**Comment by ianopolous** [comment]
@Nashatyrev It's looking like I might need more upstream changes than I was hoping. Any suggestions for how to get RelayTransport::upgradeStream working when we have a Stream not a Channel? It seems we fundamentally need a channel to set the remote peerid on for the security negotiation?

**Comment by StefanBratanov** [comment]
> Hey @ianopolous
> 
> > What are you thoughts on the direction of this: https://github.com/Peergos/nabu/compare/feat/circuit-relay-v2?expand=1
> 
> That doesn't look like a lot of changes to the core classes there. I believe it's worth to upstream. @StefanBratanov what do you think?

I think it's good addition especially since there is already a project which would require it and most of the code is already there.

**Comment by Nashatyrev** [comment]
@ianopolous, sorry for delay again, I'm OOO currently 
I'll try to look into this in a week or so

**Comment by ianopolous** [comment]
My hope is to test with a local relay once it's working. But wanted to rule out issues with the relay first. The normal way to find a relay is to try a bunch of nodes you've discovered, as it is on by default normally. We do this downstream in Nabu using our kademlia impl.

**Comment by ianopolous** [comment]
I've changed the test relay to another random node.

**Comment by ianopolous** [comment]
I've tried calling channel.pipeline().fireChannelActive() in a bunch of places including in upgradeStream after calling upgrader.establishSecureChannel(). None of it seems to have any effect.

**Comment by ianopolous** [comment]
I've added a local relay test which hits the same issue now.

**Comment by Nashatyrev** [comment]
Thanks for adding the standalone test 👍 
I can see now that 'old' handlers are not removed from the stream. You need to remove the handlers processing the circuit protocol messages to make the stream channel raw again. After removing old handlers and adding new handlers from upgrader calling `fireChannelActive()` should work I believe

**Comment by Nashatyrev** [comment]
Just leave the circuit-v2 protocol spec bookmark here: https://github.com/libp2p/specs/blob/master/relay/circuit-v2.md

**Comment by ianopolous** [comment]
Thank you @Nashatyrev that did the trick. It's now working with a remote relay. Local relay is still broken though.

**Comment by ianopolous** [comment]
Okay it's working over a local relay now too. Any suggestions before I PR, @Nashatyrev ?
