### ISSUE TITLE
Implement Noise security protocol

### ISSUE THREAD

**Issue by Nashatyrev** [libp2p/jvm-libp2p#35]
https://noiseprotocol.org/noise.html

The Noise usage for Eth2.0 is still under discussion (https://github.com/ethereum/eth2.0-specs/pull/1281/files#r302194647)

**Comment by Nashatyrev** [comment]
https://github.com/libp2p/specs/issues/195

**Comment by shahankhatch** [comment]
branch is here: libp2p/jvm-libp2p/tree/feature/makesomenoise

**Comment by Nashatyrev** [comment]
Done
