### ISSUE TITLE
Implement gossipsub IDONTWANT

### ISSUE THREAD

**Issue by StefanBratanov** [libp2p/jvm-libp2p#371]
### Description

Add support for IDONTWANT control message as per https://github.com/libp2p/specs/pull/548

### Motivation

Support GossipSub 1.2

### Requirements

1. Implement specs defined in https://github.com/libp2p/specs/pull/548

**Comment by dhuseby** [comment]
@nashatyrev and @ianopolous is there any way we can get this implemented in jvm-libp2p?

**Comment by dhuseby** [comment]
@jxs

**Comment by StefanBratanov** [comment]
> @Nashatyrev and @ianopolous is there any way we can get this implemented in jvm-libp2p?

Hi @dhuseby we would prioritise and start working on this feature in the upcoming weeks

**Comment by Nashatyrev** [comment]
Some random thoughts: 

- Upgrade Gossip version to `1.2`

Receiving `IDONTWANT`:
- Use crypro strong hashset or salted keys to mitigate hashCode attack ([comments](https://github.com/libp2p/specs/pull/548#discussion_r1565835956))
- Add a parameter configuring max `IDONTWANT` messages per peer per heartbeat
- [Optionally] consider cancelling sends which are not yet completed (not sure how it could work in practice) 

Sending `IDONTWANT`: 
- No sending if remote peer version `< 1.2` 
- Need to configure either explicit topics or message size threshold (reasonable default to me is about 16Kb) to sent `IDONTWANT`
