### ISSUE TITLE
Add Maven artifact publishing 

### ISSUE THREAD

**Issue by Nashatyrev** [libp2p/jvm-libp2p#38]

**Comment by ShadowJonathan** [comment]
What're the maven parameters + repository to add this library to a maven build?

It's marked as "done", but instructions for maven aren't visible in the readme or anywhere else.

**Comment by jezhiggins** [comment]
We only had Gradle details in the Readme. I've added Maven details as well - https://github.com/libp2p/jvm-libp2p#using-maven

**Comment by ShadowJonathan** [comment]
Thanks! 
@Nashatyrev

**Comment by Nashatyrev** [comment]
Done
