### ISSUE TITLE
Release 0.3.0 doesn't support java 11

### ISSUE THREAD

**Issue by mbaxter** [libp2p/jvm-libp2p#90]
I just tried pulling down the 0.3.0 release, but it seems to be incompatible with java 11:

> java.lang.UnsupportedClassVersionError: crypto/pb/Crypto$KeyType has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by jezhiggins** [comment]
That's on me, sorry. I'll do a new build with an older version Java and republish. Suspect I'll have to bump the version number, but will update here.

**Comment by jezhiggins** [comment]
Rebuilt with java 8 and published. I've had to bump the version so can you give version 0.3.1 a go please?
