### ISSUE TITLE
"ERROR | SecIoSecureChannel | null" log message

### ISSUE THREAD

**Issue by ajsutton** [libp2p/jvm-libp2p#95]
When connecting to peers on Lighthouse's testnet 5, we get a number of unhelpful errors in the log:
```
2020-03-17 09:35:55.124+10:00 | nioEventLoopGroup-3-19 | ERROR | SecIoSecureChannel | null
```

Most likely a `NullPointerException` is being thrown somewhere. It would be much more helpful if the full stack trace was included with the error, instead of just the exception's message.

**Comment by Nashatyrev** [comment]
Sounds like no more relevant
